### ISSUE TITLE
Text with inline emoji is wrapped in <undefined>

### ISSUE THREAD

**Issue by franky47** [florianeckerstorfer/remark-a11y-emoji#1] opened 2020-06-03 09:09 UTC
When I use this plugin on a paragraph that contains emoji, the output is wrapped in `<undefined>` tags.

Example:
```md
A line of text with 😀 inline 🎉 emoji
```

Rendered HTML:
```html
<p>
  <undefined>
    A line of text with <span role="img" aria-label="grinning face">😀</span> inline <span role="img" aria-label="party popper">🎉</span> emoji
  </undefined>
</p>
```

However, emoji on a line of their own are not wrapped in those undefined tags:

```md
👍
```
```html
<p>
  <span role="img" aria-label="thumbs up">👍</span>
</p>
```

Context:
- Next.js 9.4.4
- next-mdx-enhanced 3.0.0
- @fec/remark-a11y-emoji 1.0.0

**Comment by franky47** [comment] 2020-06-03 10:50
The AST explorer seems to indicate to insert JSX/HTML elements for the `span` tags around the text node for the emoji, rather than replace the whole node:
https://astexplorer.net/#/gist/2befce6edce1475eb4bbec001356b222/50aca75ce5eaf560163d2cf9db384bd4ed6a78b9

**Comment by florianeckerstorfer** [comment] 2020-06-04 12:24
@franky47 I believe that problem lies that `@mdx-js/mdx` converts the AST a bit differently into HTML than `remark-html`.

Since I never worked with MDX and don't have really a use for it I can at the moment not invest a lot more time to investigate this. If you could provide me with a minimal test case to reproduce this issue (bonus points for being an actual Jest test), I can look into this if we find a quick way to fix this.

**Comment by snide** [comment] 2020-09-04 18:09
@franky47 as a short term fix, you can replace the `undefined` component through `MDProvider` with a `span`.

```jsx
const components = {
  a: (props: any) => (
    <EuiLink external={props.rel !== undefined ? true : false} {...props}>
      {props.children}
    </EuiLink>
  ),
  hr: (props: any) => <EuiHorizontalRule {...props} />,
  img: (props: any) => (
    <EuiImage
      url={props.src}
      title={props.alt}
      {...props}
      allowFullScreen
      hasShadow
    />
  ),
  undefined: (props: any) => <span {...props} />,
  pre: (props: any) => <div {...props} />,
  code: (props: any) =>
    // If there are linebreaks use codeblock, otherwise code
    /\r|\n/.exec(props.children) ? (
      <EuiCodeBlock
        fontSize="m"
        paddingSize="s"
        isCopyable
        whiteSpace="pre"
        {...props}
        language={
          props.className ? props.className.replace('language-', '') : 'none'
        }
      />
    ) : (
      <EuiCode {...props} />
    ),
  Link,
  DocVideo,
  DocLink,
  EuiImage,
  EuiButton,
  DocCallOut,
};
```

and then

```jsx
<MDXProvider components={components}>{myMDXContent}</MDXProvider>
```

**Comment by franky47** [comment] 2020-09-04 18:39
Wow, that would have never occurred to me to try this.. JavaScript is wild sometimes.

**Comment by florianeckerstorfer** [comment] 2021-03-08 15:00
@franky47 @snide Could you check if this is still a problem with version 3+? I have changed how the plugin works and I think this should be fixed by this.

**Comment by franky47** [comment] 2021-03-09 08:40
I don't have the `<undefined>` tag anymore, but the emojis are not wrapped in spans either (there are comments there instead). Same result in development and production:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1174092/110441871-8b0ba280-80ba-11eb-9b8e-11caf47440c9.png">

- @fec/remark-a11y-emoji: ^3.1.0
- remark: ^13.0.0
- next-mdx-enhanced: ^5.0.0

Usage in `next.config.js` ([complete source code](https://github.com/franky47/francoisbest.com/blob/next/next.config.js#L42) for reproduction):
```js
  withMdxEnhanced({
      remarkPlugins: [
        require('@fec/remark-a11y-emoji')
      ]
    })
  ],
```

**Comment by florianeckerstorfer** [comment] 2021-04-16 13:16
@franky47 Sorry for the late reply. I was finally able to work on this issue, but I was not able to reproduce it with a minimal Next.js + next-mdx-enhanced setup. I've uploaded the [repo to Github](https://github.com/florianeckerstorfer/repro-remark-a11y-emoji-next-mdx), maybe you can reproduce it there with a more minimal setup. Your config is quite complex, maybe some of the other Remark plugin do not return a valid AST. A lot of Remark plugins do not return semantic ASTs, but each Node is a HTML node. (that's how the plugins first version worked)

<img width="468" alt="Screenshot 2021-04-16 at 15 12 21" src="https://user-images.githubusercontent.com/149201/115029516-59120b00-9ec6-11eb-8944-a349f7258e58.png">

**Comment by florianeckerstorfer** [comment] 2021-04-30 07:32
@franky47 Since I could not reproduce this issue and there is no response on this issue, I'm closing it. Feel free to reopen if you can reproduce this issue again.

**Closed by florianeckerstorfer** 2021-04-30 07:32 UTC

**Comment by franky47** [comment] 2021-04-30 07:34
Yeah sorry I haven't had the chance to try it again, I'll see if the use-case pops up in the future and I'll let you know. Thanks for your help!
